### ISSUE TITLE
Extra Image Closing Tags

### ISSUE THREAD

**Issue by Calvinoea** [brave/ads-manager-landing-page#5]
Hello,

I was curious as to whether the closing img tags were included in the index.html file for XHTML or any other reason? If not, do I have permission to remove the extra closing img tags and make the img tags self-closing?

Please find below a code example of what I observed:

`  <img src="images/Pizzahut.png" height="40px" alt="Pizza Hut Logo"></img>
          <img src="images/wd.png" height="40px" alt="Western Digital Logo"></img>
          <img src="images/Barrons.png" height="18px" alt="Barrons Logo"></img>
          <img src="images/HomeChef.png" height="40px" alt="Home Chef Logo"></img>`

Thank you.

**Comment by AlanBreck** [comment]
Removing the closing image tags in favor of self-closing tags would be great. Thank you, @Calvinoea!

**Comment by Calvinoea** [comment]
> Removing the closing image tags in favor of self-closing tags would be great. Please feel free to submit a PR. Thank you, @Calvinoea!

Thank you @AlanBreck . I'll make the changes now!

**Comment by Miyayes** [comment]
Thanks. I have removed the unnecessary `</img>` closing tags.
